# Generated by Django 5.1.4 on 2025-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_genre_readingprogress_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='decription',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=False),
        ),
    ]
