# Generated by Django 5.1.4 on 2025-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_book_cover_image_alter_book_decription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
