# Generated by Django 5.1.4 on 2025-01-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_book_cover_image_remove_book_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
