# Generated by Django 5.1.4 on 2025-01-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
