# Generated by Django 5.1.4 on 2025-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='open_lib_cover',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
