# Generated by Django 5.1.4 on 2025-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_book_open_lib_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
