# Generated by Django 5.1.4 on 2025-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_readingprogress_book_read_readingprogress_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currently_reading',
            field=models.BooleanField(default=False),
        ),
    ]
