# Generated by Django 5.1.4 on 2025-02-02 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_book_currently_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_books_cover',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='BookDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
            ],
        ),
    ]
