# Generated by Django 5.1.4 on 2025-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_book_google_books_cover_bookdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
