# Generated by Django 5.1.4 on 2025-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='total_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
