# Generated by Django 5.1.4 on 2025-02-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_userstats_total_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
